import Head from 'next/head'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

import Nav from "../components/Nav";
import Board from "../components/Board";
import { Container } from '@/components/Container';
import Icon from "../components/Icon";
import Search from '../components/Search';
import PerspectiveGrid from '@/components/PerspectiveGrid';

import players from '@/players';

import { Content, Row, FlexItem, ContentOverlay, Title } from "@/styles";

export default function Home() {
  return (
    <>
      <Head>
        <title>Leaderboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <PerspectiveGrid />
       <Content>
        <ContentOverlay></ContentOverlay>
        <Title>
            Leaderboard
          </Title>
      </Content>
      <Container>
          <Row direction="row" gap="sm">
            <Search data={players} />
            <FlexItem display="flex" items="center" cursor="pointer">
              <Icon name="layers" viewBox='0 0 512 512' size={"24"}  />
            </FlexItem>
          </Row>
        <Board />
      </Container>
    </>
  )
}
