import Head from 'next/head'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

import Nav from "../components/Nav";
import Board from "../components/Board";
import { Container } from '@/components/Container';

import { styled } from '@stitches/react';


import { useState } from 'react';

import { useTheme } from "next-themes";



const Title = styled('title', {
  display: 'block',
  fontSize: '2rem',
  color: 'white',
  fontWeight: 'bold',
  margin: '0 auto',
  paddingTop: '70px',
  paddingBottom: '70px',
});

const Content = styled('content', {
  display: 'flex',
  backgroundColor: '#2c1159',
  height: '290px',
  width: '100%',
  borderRadius: '51% 49% 49% 51% / 0% 0% 100% 100%',
  /* clipPath: 'polygon(0 0, 100% 0, 100% 20%, 94% 67%, 77% 100%, 20% 100%, 3% 66%, 0% 20%);', */
});

const SearchBar = styled('searchBar', {
  display: 'flex',
  width: '100%',
  position: 'relative',
  marginTop: '10px'
});

const Input = styled("input", {
  display: "block",
  marginBottom: "10px",
  width: '100%',
  height: '40px',
  backgroundColor: '#251e40',
  borderRadius: '7px',
  color: 'white',
  borderStyle: 'solid',
  borderColor: '#4c037a',
  borderWidth: '1px',
  outline: 0,

  "&::placeholder": {
    color: 'white',
  },

  variants: {
    size: {
      sm: {
        fontSize: "13px",
        height: "25px",
        paddingRight: "10px",
        paddingLeft: "10px",
      },
      lg: {
        fontSize: "16px",
        height: "40px",
        paddingLeft: "15px",
        paddingRight: "15px",
      },
    },
    placement: {
      iconed: {
        paddingLeft: "35px"
      }
    }
  },
});

const Icon = styled("icon", {
  position: 'absolute',
  left: '10px',
  top: '12px',
  variants: {
    color: {
      white: {
        color: '#fff',
      },
    },
  },
});



export default function Home() {


  return (
    <>
      <Head>
        <title>Leaderboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Nav />



      <Content>
      <Title>
        Leaderboard
        
      </Title>
      </Content>

      <Container>
        <SearchBar placement="iconed">
          <Icon color="white">
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"></path></svg>
          </Icon>
          <Input type="text" placeholder='Search' size="lg" placement="iconed"></Input>
        </SearchBar>
        <Board />
      </Container>




    </>
  )
}
