import Head from 'next/head'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

import Nav from "../components/Nav";
import Board from "../components/Board";
import { Container } from '@/components/Container';
import Icon from "../components/Icon";

import { styled } from '@stitches/react';


const Title = styled('title', {
  display: 'block',
  fontSize: '2rem',
  color: 'white',
  fontWeight: 'bold',
  margin: '0 auto',
  paddingTop: '70px',
  paddingBottom: '70px',
});

const Content = styled('div', {
  display: 'flex',
  backgroundColor: '#2c1159',
  height: '290px',
  width: '100%',
  borderRadius: '51% 49% 49% 51% / 0% 0% 100% 100%',
});

const SearchBar = styled('div', {
  display: 'flex',
  width: '100%',
  position: 'relative',
  marginTop: '10px'
});

const Input = styled("input", {
  display: "block",
  marginBottom: "10px",
  width: '100%',
  height: '40px',
  backgroundColor: '#251e40',
  borderRadius: '7px',
  color: 'white',
  borderStyle: 'solid',
  borderColor: 'rgb(61 45 126)',
  borderWidth: '1px',
  outline: 0,

  "&::placeholder": {
    color: 'white',
  },

  variants: {
    size: {
      sm: {
        fontSize: "13px",
        height: "25px",
        paddingRight: "10px",
        paddingLeft: "10px",
      },
      lg: {
        fontSize: "16px",
        height: "50px",
        paddingLeft: "45px",
        paddingRight: "15px",
      },
    },
  },
});

const InputIcon = styled("div", {
  position: 'absolute',
  left: '20px',
  top: '16px',
  variants: {
    color: {
      white: {
        color: '#fff',
      },
    },
  },
});


const FlexItem = styled("div", {
  backgroundColor: '#251e40',
  borderRadius: '7px',
  borderStyle: 'solid',
  borderColor: 'rgb(61 45 126)',
  borderWidth: '1px',
  height: '50px',
  paddingLeft: '15px',
  paddingRight: '15px',
  variants: {
    cursor: {
      pointer: {
        cursor: 'pointer'
      }
    },
    display: {
      flex: {
        display: 'flex',
      },
    },
    items: {
      center: {
        alignItems: 'center',
      }
    }
  },
});


const Row = styled("div", {
  display: 'flex',
  alignItems: 'center',
  variants: {
    direction: {
      column: {
        flexDirection: 'column',
      },
      row: {
        flexDirection: 'row'
      },
    },
    gap: {
      sm: {
        gap: '10px'
      }
    }
  },
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Leaderboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <Content>
      <Title>
        Leaderboard
      </Title>
      </Content>

      <Container>

          <Row direction="row" gap="sm">
            <SearchBar>
              <InputIcon><Icon name="search" /></InputIcon>
              <Input type="text" placeholder='Search' size="lg"></Input>
            </SearchBar>
            <FlexItem display="flex" items="center" cursor="pointer">
              <Icon name="layers" viewBox='0 0 512 512' size={"24"}  />
            </FlexItem>
          </Row>






        <Board />
      </Container>
    </>
  )
}
